/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search the Pokédex */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Suggest entity names and vocabulary concepts while the user types */
        get: operations["suggest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities/{kind}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one Pokémon, move or ability with its related entities */
        get: operations["getEntity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report whether the dataset is loaded */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /** @enum {string} */
        EntityKind: "pokemon" | "move" | "ability";
        EntityRef: {
            kind: components["schemas"]["EntityKind"];
            name: string;
        };
        SearchResponse: {
            /** @description The query after trimming. */
            query: string;
            /** @description The query rewritten in the product vocabulary; it is interpreted exactly as the original. Null when no term was recognized. */
            canonical_query: string | null;
            /** @enum {string} */
            outcome: "results" | "empty";
            interpretation: components["schemas"]["Interpretation"];
            /** @description Every term of the query, in order, with the role it was recognized in. */
            terms: components["schemas"]["Term"][];
            /** @description Honest caveats, such as ignored terms, an approximate match or a mechanic absent from the dataset. */
            notices: components["schemas"]["Notice"][];
            /** @description Why nothing answers the query. Required when the outcome is empty. */
            explanation: string | null;
            /** @description Names close to the query and example queries, offered when the outcome is empty. */
            suggestions: components["schemas"]["Suggestion"][];
            /** @description The entity the query names exactly, or the only name it is a prefix of. */
            best_match: components["schemas"]["EntityRef"] | null;
            /** @description Ways to adjust each recognized constraint, each with the canonical query that applies it. */
            refinements: components["schemas"]["Refinement"][];
            /** @description One section per entity kind with results, most relevant kind first. */
            sections: components["schemas"]["Section"][];
        } & unknown;
        Interpretation: {
            /** @description Plans the query was read as. Each plan is conjunctive: its results satisfy all of its constraints. Several plans mean the query was ambiguous, such as psychic, a type and a move. */
            alternatives: components["schemas"]["SearchPlan"][];
            /** @description Human-readable description of the plans, shown to the user. */
            summary: string;
        };
        SearchPlan: {
            /** @description Kinds the results are restricted to; empty means any kind a constraint applies to. */
            kinds: components["schemas"]["EntityKind"][];
            /** @description Name term matched against entity names. */
            name: string | null;
            dex_number: number | null;
            types: string[];
            characteristics: components["schemas"]["Characteristic"][];
            /** @description Stats to rank by. One stat ranks by its value; several rank by their mean percentile. */
            stat_sort: components["schemas"]["StatSort"][];
            /** @description Comparisons every result satisfies. */
            stat_filters: components["schemas"]["StatFilter"][];
            /** @description Damage classes every move result has. */
            damage_classes: ("physical" | "special" | "status")[];
            effect: components["schemas"]["EffectConstraint"] | null;
            weather: components["schemas"]["WeatherConstraint"] | null;
            relation: components["schemas"]["RelationConstraint"] | null;
        };
        Characteristic: {
            /** @enum {string} */
            facet: "genus" | "color" | "habitat" | "legendary" | "mythical" | "description";
            /** @description Normalized value, such as fox, blue or cave; true for legendary and mythical. */
            value: string;
        };
        /**
         * @description A Pokémon base stat, a derived Pokémon stat (bulk is hp plus defense plus special defense, offense the higher of attack and special attack), or a move attribute.
         * @enum {string}
         */
        StatName: "hp" | "attack" | "defense" | "special-attack" | "special-defense" | "speed" | "total" | "bulk" | "offense" | "power" | "accuracy" | "pp" | "priority";
        StatSort: {
            stat: components["schemas"]["StatName"];
            /** @enum {string} */
            direction: "asc" | "desc";
        };
        StatFilter: {
            stat: components["schemas"]["StatName"];
            /** @enum {string} */
            comparator: "gt" | "gte" | "lt" | "lte";
            value: number;
        };
        EffectConstraint: {
            /** @description Effect concept, such as sleep or paralysis. */
            effect: string;
            /** @enum {string} */
            mode: "causes" | "prevents";
            /** @enum {string|null} */
            target: "opponent" | "user" | null;
        };
        WeatherConstraint: {
            /** @description Weather concept, such as rain or sun. */
            weather: string;
            /** @description Stat the weather effect must raise, as in faster in the rain. */
            stat: components["schemas"]["StatName"] | null;
        };
        RelationConstraint: {
            /**
             * @description learns-move and has-ability return Pokémon; learned-by returns the moves of a Pokémon; carried-by returns the abilities of a Pokémon.
             * @enum {string}
             */
            predicate: "learns-move" | "has-ability" | "learned-by" | "carried-by";
            entity: components["schemas"]["EntityRef"];
        };
        Term: {
            /** @description The term as written in the query. */
            text: string;
            /** @enum {string} */
            role: "name" | "dex-number" | "kind" | "type" | "characteristic" | "stat" | "direction" | "comparator" | "number" | "effect" | "mode" | "target" | "weather" | "relation" | "filler" | "ignored";
            /** @description The normalized concept, such as electric, speed:desc, desc, gte or 100; null for filler and ignored terms. */
            value: string | null;
        };
        Notice: {
            /** @description Stable identifier, such as ignored-terms, approximate-match or missing-mechanic. */
            code: string;
            message: string;
        };
        Suggestion: {
            /** @enum {string} */
            kind: "name" | "example";
            label: string;
            query: string;
        };
        Refinement: {
            /** @description Identifier of the constraint the refinement adjusts, such as type:electric or sort. */
            constraint: string;
            /** @enum {string} */
            action: "add" | "remove" | "replace";
            label: string;
            /** @description Canonical query that applies the refinement. */
            query: string;
        };
        Section: {
            kind: components["schemas"]["EntityKind"];
            /** @description Number of results of this kind across all pages. */
            total: number;
            results: components["schemas"]["Result"][];
            /** @description Cursor for the next page of this section; null on the last page. */
            next_cursor: string | null;
        };
        Result: components["schemas"]["PokemonResult"] | components["schemas"]["MoveResult"] | components["schemas"]["AbilityResult"];
        ResultBase: {
            kind: components["schemas"]["EntityKind"];
            /** @description Kebab-case dataset name. */
            name: string;
            /** @description Position within the section, continuing across pages. */
            rank: number;
            reasons: components["schemas"]["Reason"][];
        };
        Reason: {
            /** @enum {string} */
            type: "name-exact" | "name-prefix" | "name-infix" | "name-fuzzy" | "dex-number" | "type-filter" | "characteristic" | "stat-rank" | "stat-filter" | "effect" | "weather" | "learns-move" | "has-ability" | "learned-by" | "carried-by" | "description-match";
            /** @description Human-readable explanation shown to the user. */
            detail: string;
            related: components["schemas"]["EntityRef"] | null;
            /** @description Probability that the effect happens, for effect reasons. */
            probability: number | null;
            /** @enum {string|null} */
            mode: "causes" | "prevents" | "requires" | null;
            /** @enum {string|null} */
            target: "opponent" | "user" | null;
            /** @enum {string|null} */
            weather_role: "setter" | "benefit" | "protection" | "mixed" | "drawback" | null;
        };
        Stats: {
            hp: number;
            attack: number;
            defense: number;
            "special-attack": number;
            "special-defense": number;
            speed: number;
        };
        PokemonResult: components["schemas"]["ResultBase"] & {
            /** @constant */
            kind: "pokemon";
            id: number;
            types: string[];
            stats: components["schemas"]["Stats"];
            abilities: string[];
            genus: string | null;
            description: string | null;
            /** Format: uri */
            sprite_url: string | null;
            /** Format: uri */
            artwork_url: string | null;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "pokemon";
        };
        MoveResult: components["schemas"]["ResultBase"] & {
            /** @constant */
            kind: "move";
            id: number;
            type: string;
            /** @enum {string} */
            damage_class: "physical" | "special" | "status";
            power: number | null;
            accuracy: number | null;
            pp: number | null;
            priority: number;
            effect_chance: number | null;
            short_effect: string | null;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "move";
        };
        AbilityResult: components["schemas"]["ResultBase"] & {
            /** @constant */
            kind: "ability";
            id: number;
            short_effect: string | null;
            generation: string;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "ability";
        };
        SuggestResponse: {
            suggestions: components["schemas"]["SuggestItem"][];
        };
        SuggestItem: {
            /** @enum {string} */
            kind: "entity" | "concept";
            label: string;
            /** @description Query to run when the suggestion is selected. */
            query: string;
            entity: components["schemas"]["EntityRef"] | null;
            concept: {
                /** @enum {string} */
                role: "kind" | "type" | "characteristic" | "stat" | "direction" | "comparator" | "effect" | "mode" | "target" | "weather" | "relation";
                value: string;
            } | null;
        };
        EntityDetail: components["schemas"]["PokemonDetail"] | components["schemas"]["MoveDetail"] | components["schemas"]["AbilityDetail"];
        PokemonDetail: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "pokemon";
            id: number;
            name: string;
            types: string[];
            stats: components["schemas"]["Stats"];
            abilities: string[];
            moves: string[];
            genus: string | null;
            description: string | null;
            height_decimetres: number;
            weight_hectograms: number;
            color: string;
            shape: string | null;
            habitat: string | null;
            is_legendary: boolean;
            is_mythical: boolean;
            /** @description Names of the Pokémon sharing its evolution chain, in Pokédex order. */
            evolution_family: string[];
            /** Format: uri */
            sprite_url: string | null;
            /** Format: uri */
            artwork_url: string | null;
        };
        MoveDetail: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "move";
            id: number;
            name: string;
            type: string;
            /** @enum {string} */
            damage_class: "physical" | "special" | "status";
            power: number | null;
            accuracy: number | null;
            pp: number | null;
            priority: number;
            effect_chance: number | null;
            short_effect: string | null;
            effect: string | null;
            learned_by: string[];
        };
        AbilityDetail: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "ability";
            id: number;
            name: string;
            short_effect: string | null;
            effect: string | null;
            generation: string;
            pokemon: string[];
        };
        ErrorResponse: {
            error: {
                /** @enum {string} */
                code: "invalid_query" | "invalid_parameter" | "not_found" | "internal_error";
                message: string;
            };
        };
    };
    responses: {
        /** @description The entity tag in If-None-Match still matches; the stored response is current. */
        NotModified: {
            headers: {
                ETag: components["headers"]["ETag"];
                "Cache-Control": components["headers"]["CacheControl"];
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Unexpected failure. No internal detail is exposed. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "internal_error",
                 *         "message": "The search failed unexpectedly."
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: {
        /** @description Weak entity tag of the response body. Sending it back in If-None-Match yields 304 Not Modified while the response is unchanged. */
        ETag: string;
        /** @description Always no-cache, so every reuse of a stored response is validated. */
        CacheControl: "no-cache";
    };
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    search: {
        parameters: {
            query: {
                /** @description Free-text query, trimmed, between 2 and 200 characters. */
                q: string;
                /** @description Restrict the response to the section of one entity kind. Required with a cursor. */
                kind?: components["schemas"]["EntityKind"];
                /** @description Maximum number of results per section. */
                limit?: number;
                /** @description Opaque next_cursor of a section, sent with the same q and the section's kind. */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The query is valid. The outcome says whether anything answers it. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            304: components["responses"]["NotModified"];
            /** @description The query or a parameter breaks the input rules. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "invalid_query",
                     *         "message": "The query must contain between 2 and 200 characters."
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    suggest: {
        parameters: {
            query: {
                /** @description Partial query, trimmed, between 2 and 200 characters. */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Suggestions, best first. The list may be empty. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestResponse"];
                };
            };
            304: components["responses"]["NotModified"];
            /** @description The partial query breaks the input rules. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getEntity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: components["schemas"]["EntityKind"];
                /** @description Kebab-case dataset name. */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The entity and its relations. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityDetail"];
                };
            };
            304: components["responses"]["NotModified"];
            /** @description No entity of this kind has this name. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "not_found",
                     *         "message": "No move is named 'rain-dance'."
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The service is ready. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ok";
                        dataset_sha256: string;
                    };
                };
            };
        };
    };
}
