import type { EntityDetail } from "../../api/contract";

export const pikachuDetail = {
  kind: "pokemon",
  id: 25,
  name: "pikachu",
  types: ["electric"],
  stats: {
    hp: 35,
    attack: 55,
    defense: 40,
    "special-attack": 50,
    "special-defense": 50,
    speed: 90,
  },
  abilities: ["lightning-rod", "static"],
  moves: [
    "agility",
    "bide",
    "body-slam",
    "double-edge",
    "double-team",
    "flash",
    "growl",
    "light-screen",
    "mega-kick",
    "mega-punch",
    "mimic",
    "pay-day",
    "quick-attack",
    "rage",
    "reflect",
    "rest",
    "seismic-toss",
    "skull-bash",
    "slam",
    "submission",
    "substitute",
    "surf",
    "swift",
    "tail-whip",
    "take-down",
    "thunder",
    "thunder-shock",
    "thunder-wave",
    "thunderbolt",
    "toxic",
  ],
  genus: "Mouse Pokémon",
  description:
    "When several of these POKéMON gather, their electricity could build and cause lightning storms.",
  height_decimetres: 4,
  weight_hectograms: 60,
  color: "yellow",
  shape: "quadruped",
  habitat: "forest",
  is_legendary: false,
  is_mythical: false,
  evolution_family: ["pikachu", "raichu"],
  sprite_url: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png",
  artwork_url:
    "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png",
} satisfies EntityDetail;
