import type { SearchResponse } from "../../api/contract";

export const psychicSearch = {
  query: "psychic",
  canonical_query: "psychic",
  outcome: "results",
  interpretation: {
    alternatives: [
      {
        kinds: [],
        name: null,
        dex_number: null,
        types: ["psychic"],
        characteristics: [],
        stat_sort: [],
        stat_filters: [],
        damage_classes: [],
        effect: null,
        weather: null,
        relation: null,
      },
      {
        kinds: [],
        name: "psychic",
        dex_number: null,
        types: [],
        characteristics: [],
        stat_sort: [],
        stat_filters: [],
        damage_classes: [],
        effect: null,
        weather: null,
        relation: null,
      },
    ],
    summary: "of type psychic or names matching 'psychic'",
  },
  terms: [
    {
      text: "psychic",
      role: "type",
      value: "psychic",
    },
  ],
  notices: [],
  explanation: null,
  suggestions: [],
  best_match: {
    kind: "move",
    name: "psychic",
  },
  refinements: [
    {
      constraint: "sort:speed",
      action: "add",
      label: "Fastest first",
      query: "highest speed psychic",
    },
  ],
  sections: [
    {
      kind: "pokemon",
      total: 14,
      results: [
        {
          name: "abra",
          rank: 1,
          reasons: [
            {
              type: "type-filter",
              detail: "Type psychic",
              related: null,
              probability: null,
              mode: null,
              target: null,
              weather_role: null,
            },
          ],
          kind: "pokemon",
          id: 63,
          types: ["psychic"],
          stats: {
            hp: 25,
            attack: 20,
            defense: 15,
            "special-attack": 105,
            "special-defense": 55,
            speed: 90,
          },
          abilities: ["inner-focus", "magic-guard", "synchronize"],
          genus: "Psi Pokémon",
          description:
            "Using its ability to read minds, it will identify impending danger and TELEPORT to safety.",
          sprite_url:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/63.png",
          artwork_url:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/63.png",
        },
        {
          name: "kadabra",
          rank: 2,
          reasons: [
            {
              type: "type-filter",
              detail: "Type psychic",
              related: null,
              probability: null,
              mode: null,
              target: null,
              weather_role: null,
            },
          ],
          kind: "pokemon",
          id: 64,
          types: ["psychic"],
          stats: {
            hp: 40,
            attack: 35,
            defense: 30,
            "special-attack": 120,
            "special-defense": 70,
            speed: 105,
          },
          abilities: ["inner-focus", "magic-guard", "synchronize"],
          genus: "Psi Pokémon",
          description:
            "It emits special alpha waves from its body that induce headaches just by being close by.",
          sprite_url:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/64.png",
          artwork_url:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/64.png",
        },
        {
          name: "alakazam",
          rank: 3,
          reasons: [
            {
              type: "type-filter",
              detail: "Type psychic",
              related: null,
              probability: null,
              mode: null,
              target: null,
              weather_role: null,
            },
          ],
          kind: "pokemon",
          id: 65,
          types: ["psychic"],
          stats: {
            hp: 55,
            attack: 50,
            defense: 45,
            "special-attack": 135,
            "special-defense": 95,
            speed: 120,
          },
          abilities: ["inner-focus", "magic-guard", "synchronize"],
          genus: "Psi Pokémon",
          description:
            "Its brain can out perform a super computer. Its intelligence quotient is said to be 5,000.",
          sprite_url:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/65.png",
          artwork_url:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/65.png",
        },
        {
          name: "slowpoke",
          rank: 4,
          reasons: [
            {
              type: "type-filter",
              detail: "Type psychic",
              related: null,
              probability: null,
              mode: null,
              target: null,
              weather_role: null,
            },
          ],
          kind: "pokemon",
          id: 79,
          types: ["water", "psychic"],
          stats: {
            hp: 90,
            attack: 65,
            defense: 65,
            "special-attack": 40,
            "special-defense": 40,
            speed: 15,
          },
          abilities: ["oblivious", "own-tempo", "regenerator"],
          genus: "Dopey Pokémon",
          description:
            "It is always so absent-minded that it won't react, even if its flavorful tail is bitten.",
          sprite_url:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/79.png",
          artwork_url:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/79.png",
        },
        {
          name: "slowbro",
          rank: 5,
          reasons: [
            {
              type: "type-filter",
              detail: "Type psychic",
              related: null,
              probability: null,
              mode: null,
              target: null,
              weather_role: null,
            },
          ],
          kind: "pokemon",
          id: 80,
          types: ["water", "psychic"],
          stats: {
            hp: 95,
            attack: 75,
            defense: 110,
            "special-attack": 100,
            "special-defense": 80,
            speed: 30,
          },
          abilities: ["oblivious", "own-tempo", "regenerator"],
          genus: "Hermit Crab Pokémon",
          description:
            "The SHELLDER that is latched onto SLOWPOKE's tail is said to feed on the host's left over scraps.",
          sprite_url:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/80.png",
          artwork_url:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/80.png",
        },
      ],
      next_cursor:
        "eyJraW5kIjoicG9rZW1vbiIsIm9mZnNldCI6NSwiZmluZ2VycHJpbnQiOiJlMzI4NjAyZWFmYzJiNDg3In0",
    },
    {
      kind: "move",
      total: 15,
      results: [
        {
          name: "psybeam",
          rank: 1,
          reasons: [
            {
              type: "type-filter",
              detail: "Type psychic",
              related: null,
              probability: null,
              mode: null,
              target: null,
              weather_role: null,
            },
          ],
          kind: "move",
          id: 60,
          type: "psychic",
          damage_class: "special",
          power: 65,
          accuracy: 100,
          pp: 20,
          priority: 0,
          effect_chance: 10,
          short_effect: "Has a chance to confuse the target.",
        },
        {
          name: "confusion",
          rank: 2,
          reasons: [
            {
              type: "type-filter",
              detail: "Type psychic",
              related: null,
              probability: null,
              mode: null,
              target: null,
              weather_role: null,
            },
          ],
          kind: "move",
          id: 93,
          type: "psychic",
          damage_class: "special",
          power: 50,
          accuracy: 100,
          pp: 25,
          priority: 0,
          effect_chance: 10,
          short_effect: "Has a chance to confuse the target.",
        },
        {
          name: "psychic",
          rank: 3,
          reasons: [
            {
              type: "type-filter",
              detail: "Type psychic",
              related: null,
              probability: null,
              mode: null,
              target: null,
              weather_role: null,
            },
          ],
          kind: "move",
          id: 94,
          type: "psychic",
          damage_class: "special",
          power: 90,
          accuracy: 100,
          pp: 10,
          priority: 0,
          effect_chance: 10,
          short_effect: "Has a chance to lower the target's Special Defense by one stage.",
        },
        {
          name: "hypnosis",
          rank: 4,
          reasons: [
            {
              type: "type-filter",
              detail: "Type psychic",
              related: null,
              probability: null,
              mode: null,
              target: null,
              weather_role: null,
            },
          ],
          kind: "move",
          id: 95,
          type: "psychic",
          damage_class: "status",
          power: null,
          accuracy: 60,
          pp: 20,
          priority: 0,
          effect_chance: null,
          short_effect: "Puts the target to sleep.",
        },
        {
          name: "meditate",
          rank: 5,
          reasons: [
            {
              type: "type-filter",
              detail: "Type psychic",
              related: null,
              probability: null,
              mode: null,
              target: null,
              weather_role: null,
            },
          ],
          kind: "move",
          id: 96,
          type: "psychic",
          damage_class: "status",
          power: null,
          accuracy: null,
          pp: 40,
          priority: 0,
          effect_chance: null,
          short_effect: "Raises the user's Attack by one stage.",
        },
      ],
      next_cursor:
        "eyJraW5kIjoibW92ZSIsIm9mZnNldCI6NSwiZmluZ2VycHJpbnQiOiJlMzI4NjAyZWFmYzJiNDg3In0",
    },
  ],
} satisfies SearchResponse;
