import type { SearchResponse } from "../../api/contract";

export const sunTeamSearch = {
  query: "sun team",
  canonical_query: "sun",
  outcome: "results",
  interpretation: {
    alternatives: [
      {
        kinds: [],
        name: null,
        dex_number: null,
        types: [],
        characteristics: [],
        stat_sort: [],
        stat_filters: [],
        damage_classes: [],
        effect: null,
        weather: {
          weather: "sun",
          stat: null,
        },
        relation: null,
      },
    ],
    summary: "linked to sun",
  },
  terms: [
    {
      text: "sun",
      role: "weather",
      value: "sun",
    },
    {
      text: "team",
      role: "filler",
      value: null,
    },
  ],
  notices: [],
  explanation: null,
  suggestions: [],
  best_match: null,
  refinements: [],
  sections: [
    {
      kind: "ability",
      total: 7,
      results: [
        {
          name: "drought",
          rank: 1,
          reasons: [
            {
              type: "weather",
              detail: "Sets sun",
              related: null,
              probability: null,
              mode: null,
              target: null,
              weather_role: "setter",
            },
          ],
          kind: "ability",
          id: 70,
          short_effect: "Summons strong sunlight that lasts indefinitely upon entering battle.",
          generation: "generation-iii",
        },
        {
          name: "chlorophyll",
          rank: 2,
          reasons: [
            {
              type: "weather",
              detail: "Benefits from sun, raises speed",
              related: null,
              probability: null,
              mode: null,
              target: null,
              weather_role: "benefit",
            },
          ],
          kind: "ability",
          id: 34,
          short_effect: "Doubles Speed during strong sunlight.",
          generation: "generation-iii",
        },
        {
          name: "solar-power",
          rank: 3,
          reasons: [
            {
              type: "weather",
              detail: "Benefits from sun",
              related: null,
              probability: null,
              mode: null,
              target: null,
              weather_role: "benefit",
            },
          ],
          kind: "ability",
          id: 94,
          short_effect:
            "Increases Special Attack to 1.5× but costs 1/8 max HP after each turn during strong sunlight.",
          generation: "generation-iv",
        },
        {
          name: "leaf-guard",
          rank: 4,
          reasons: [
            {
              type: "weather",
              detail: "Benefits from sun",
              related: null,
              probability: null,
              mode: null,
              target: null,
              weather_role: "benefit",
            },
          ],
          kind: "ability",
          id: 102,
          short_effect: "Protects against major status ailments during strong sunlight.",
          generation: "generation-iv",
        },
        {
          name: "harvest",
          rank: 5,
          reasons: [
            {
              type: "weather",
              detail: "Benefits from sun",
              related: null,
              probability: null,
              mode: null,
              target: null,
              weather_role: "benefit",
            },
          ],
          kind: "ability",
          id: 139,
          short_effect:
            "Has a 50% chance of restoring a used Berry after each turn if the Pokémon has held no items in the meantime.",
          generation: "generation-v",
        },
      ],
      next_cursor:
        "eyJraW5kIjoiYWJpbGl0eSIsIm9mZnNldCI6NSwiZmluZ2VycHJpbnQiOiI2MDAyNjYyNDZiMWQwYTQ3In0",
    },
    {
      kind: "move",
      total: 3,
      results: [
        {
          name: "growth",
          rank: 1,
          reasons: [
            {
              type: "weather",
              detail: "Benefits from sun",
              related: null,
              probability: null,
              mode: null,
              target: null,
              weather_role: "benefit",
            },
          ],
          kind: "move",
          id: 74,
          type: "normal",
          damage_class: "status",
          power: null,
          accuracy: null,
          pp: 20,
          priority: 0,
          effect_chance: null,
          short_effect: "Raises the user's Attack and Special Attack by one stage.",
        },
        {
          name: "solar-beam",
          rank: 2,
          reasons: [
            {
              type: "weather",
              detail: "Benefits from sun",
              related: null,
              probability: null,
              mode: null,
              target: null,
              weather_role: "benefit",
            },
          ],
          kind: "move",
          id: 76,
          type: "grass",
          damage_class: "special",
          power: 120,
          accuracy: 100,
          pp: 10,
          priority: 0,
          effect_chance: null,
          short_effect: "Requires a turn to charge before attacking.",
        },
        {
          name: "thunder",
          rank: 3,
          reasons: [
            {
              type: "weather",
              detail: "Is hindered by sun",
              related: null,
              probability: null,
              mode: null,
              target: null,
              weather_role: "drawback",
            },
          ],
          kind: "move",
          id: 87,
          type: "electric",
          damage_class: "special",
          power: 110,
          accuracy: 70,
          pp: 10,
          priority: 0,
          effect_chance: 30,
          short_effect: "Has a chance to paralyze the target.",
        },
      ],
      next_cursor: null,
    },
    {
      kind: "pokemon",
      total: 32,
      results: [
        {
          name: "vulpix",
          rank: 1,
          reasons: [
            {
              type: "weather",
              detail: "Sets sun through drought",
              related: {
                kind: "ability",
                name: "drought",
              },
              probability: null,
              mode: null,
              target: null,
              weather_role: "setter",
            },
          ],
          kind: "pokemon",
          id: 37,
          types: ["fire"],
          stats: {
            hp: 38,
            attack: 41,
            defense: 40,
            "special-attack": 50,
            "special-defense": 65,
            speed: 65,
          },
          abilities: ["drought", "flash-fire"],
          genus: "Fox Pokémon",
          description:
            "At the time of birth, it has just one tail. The tail splits from its tip as it grows older.",
          sprite_url:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/37.png",
          artwork_url:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/37.png",
        },
        {
          name: "ninetales",
          rank: 2,
          reasons: [
            {
              type: "weather",
              detail: "Sets sun through drought",
              related: {
                kind: "ability",
                name: "drought",
              },
              probability: null,
              mode: null,
              target: null,
              weather_role: "setter",
            },
          ],
          kind: "pokemon",
          id: 38,
          types: ["fire"],
          stats: {
            hp: 73,
            attack: 76,
            defense: 75,
            "special-attack": 81,
            "special-defense": 100,
            speed: 100,
          },
          abilities: ["drought", "flash-fire"],
          genus: "Fox Pokémon",
          description:
            "Very smart and very vengeful. Grabbing one of its many tails could result in a 1000-year curse.",
          sprite_url:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/38.png",
          artwork_url:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/38.png",
        },
        {
          name: "tangela",
          rank: 3,
          reasons: [
            {
              type: "weather",
              detail: "Benefits from sun through growth",
              related: {
                kind: "move",
                name: "growth",
              },
              probability: null,
              mode: null,
              target: null,
              weather_role: "benefit",
            },
            {
              type: "weather",
              detail: "Benefits from sun through solar-beam",
              related: {
                kind: "move",
                name: "solar-beam",
              },
              probability: null,
              mode: null,
              target: null,
              weather_role: "benefit",
            },
            {
              type: "weather",
              detail: "Benefits from sun, raises speed through chlorophyll",
              related: {
                kind: "ability",
                name: "chlorophyll",
              },
              probability: null,
              mode: null,
              target: null,
              weather_role: "benefit",
            },
            {
              type: "weather",
              detail: "Benefits from sun through leaf-guard",
              related: {
                kind: "ability",
                name: "leaf-guard",
              },
              probability: null,
              mode: null,
              target: null,
              weather_role: "benefit",
            },
          ],
          kind: "pokemon",
          id: 114,
          types: ["grass"],
          stats: {
            hp: 65,
            attack: 55,
            defense: 115,
            "special-attack": 100,
            "special-defense": 40,
            speed: 60,
          },
          abilities: ["chlorophyll", "leaf-guard", "regenerator"],
          genus: "Vine Pokémon",
          description:
            "The whole body is swathed with wide vines that are similar to sea weed. Its vines shake as it walks.",
          sprite_url:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/114.png",
          artwork_url:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/114.png",
        },
        {
          name: "exeggcute",
          rank: 4,
          reasons: [
            {
              type: "weather",
              detail: "Benefits from sun through solar-beam",
              related: {
                kind: "move",
                name: "solar-beam",
              },
              probability: null,
              mode: null,
              target: null,
              weather_role: "benefit",
            },
            {
              type: "weather",
              detail: "Benefits from sun, raises speed through chlorophyll",
              related: {
                kind: "ability",
                name: "chlorophyll",
              },
              probability: null,
              mode: null,
              target: null,
              weather_role: "benefit",
            },
            {
              type: "weather",
              detail: "Benefits from sun through harvest",
              related: {
                kind: "ability",
                name: "harvest",
              },
              probability: null,
              mode: null,
              target: null,
              weather_role: "benefit",
            },
          ],
          kind: "pokemon",
          id: 102,
          types: ["grass", "psychic"],
          stats: {
            hp: 60,
            attack: 40,
            defense: 80,
            "special-attack": 60,
            "special-defense": 45,
            speed: 40,
          },
          abilities: ["chlorophyll", "harvest"],
          genus: "Egg Pokémon",
          description:
            "Using telepathy only they can receive, they always form a cluster of six EXEGGCUTE.",
          sprite_url:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/102.png",
          artwork_url:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/102.png",
        },
        {
          name: "exeggutor",
          rank: 5,
          reasons: [
            {
              type: "weather",
              detail: "Benefits from sun through solar-beam",
              related: {
                kind: "move",
                name: "solar-beam",
              },
              probability: null,
              mode: null,
              target: null,
              weather_role: "benefit",
            },
            {
              type: "weather",
              detail: "Benefits from sun, raises speed through chlorophyll",
              related: {
                kind: "ability",
                name: "chlorophyll",
              },
              probability: null,
              mode: null,
              target: null,
              weather_role: "benefit",
            },
            {
              type: "weather",
              detail: "Benefits from sun through harvest",
              related: {
                kind: "ability",
                name: "harvest",
              },
              probability: null,
              mode: null,
              target: null,
              weather_role: "benefit",
            },
          ],
          kind: "pokemon",
          id: 103,
          types: ["grass", "psychic"],
          stats: {
            hp: 95,
            attack: 95,
            defense: 85,
            "special-attack": 125,
            "special-defense": 75,
            speed: 55,
          },
          abilities: ["chlorophyll", "harvest"],
          genus: "Coconut Pokémon",
          description:
            "Legend has it that on rare occasions, one of its heads will drop off and continue on as an EXEGGCUTE.",
          sprite_url:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/103.png",
          artwork_url:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/103.png",
        },
      ],
      next_cursor:
        "eyJraW5kIjoicG9rZW1vbiIsIm9mZnNldCI6NSwiZmluZ2VycHJpbnQiOiI2MDAyNjYyNDZiMWQwYTQ3In0",
    },
  ],
} satisfies SearchResponse;
